import type { ArtistSlug } from "@/lib/artists/types";
import type { CategorySlug } from "./categories";
export interface CMSProduct {
  id?: string;
  handle: string;
  title: string;
  shortDescription?: string;
  priceBRL: number;
  compareAtPriceBRL?: number;
  image: string;
  galleryImages?: string[];
  artistSlug: ArtistSlug | "house";
  category: CategorySlug;
  tags?: string[];
  isDropLive?: boolean;
  isSoldOut?: boolean;
  isPreOrder?: boolean;
  sizes?: { label: string; available: boolean }[];
  stockNote?: string;
  shopifyVariantId?: string;
  shopifyCollectionHandle?: string;
}
// Catálogo real da 30praum.store, capturado em jul/2026 (fotos do CDN oficial da loja).
export const STATIC_PRODUCTS: CMSProduct[] = [
  {
    handle: "bandana-isso-e-trap-preta-merch-brandao-oficial",
    title: "Bandana Preta ISSO É TRAP",
    priceBRL: 49,
    image: "/products/bandana-isso-e-trap-preta-merch-brandao-oficial/1.webp",
    artistSlug: "brandao",
    isDropLive: true,
    category: "acessorios",
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "regata-canelada-preta-merch-brandao-oficial",
    title: "Regata Canelada Preta POMBA",
    priceBRL: 129,
    image: "/products/regata-canelada-preta-merch-brandao-oficial/1.webp",
    galleryImages: ["/products/regata-canelada-preta-merch-brandao-oficial/2.webp", "/products/regata-canelada-preta-merch-brandao-oficial/3.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: false }, { label: "M", available: false }, { label: "G", available: false }, { label: "GG", available: false }, { label: "EGG", available: true }, { label: "G1", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "blusa-de-moletom-com-ziper-preta-merch-brandao-oficial",
    title: "Blusa de Moletom com Zíper Preta WARZONE",
    priceBRL: 299,
    image: "/products/blusa-de-moletom-com-ziper-preta-merch-brandao-oficial/1.webp",
    galleryImages: ["/products/moletom-com-ziper-merch-brandao/4.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "moletons",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: false }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-preta-merch-brandao-oficial",
    title: "Camiseta Preta RAIO X",
    priceBRL: 129,
    image: "/products/camiseta-preta-merch-brandao-oficial/1.webp",
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "bandana-merch-brandao",
    title: "Bandana Branca ISSO É TRAP",
    priceBRL: 49,
    image: "/products/bandana-merch-brandao/1.webp",
    artistSlug: "brandao",
    isDropLive: true,
    category: "acessorios",
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "regata-canelada-merch-brandao",
    title: "Regata Canelada Off White ISSO É TRAP",
    priceBRL: 129,
    image: "/products/regata-canelada-merch-brandao/1.webp",
    galleryImages: ["/products/regata-canelada-merch-brandao/2.webp", "/products/camiseta-merch-brandao/3.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "moletom-com-ziper-merch-brandao",
    title: "Blusa de Moletom com Zíper Off White ISSO É TRAP",
    priceBRL: 299,
    image: "/products/moletom-com-ziper-merch-brandao/1.webp",
    galleryImages: ["/products/moletom-com-ziper-merch-brandao/2.webp", "/products/moletom-com-ziper-merch-brandao/3.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "moletons",
    isSoldOut: true,
    sizes: [{ label: "P", available: false }, { label: "M", available: false }, { label: "G", available: false }, { label: "GG", available: false }, { label: "EGG", available: false }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-merch-brandao",
    title: "Camiseta Off White ISSO É TRAP",
    priceBRL: 129,
    image: "/products/camiseta-merch-brandao/1.webp",
    galleryImages: ["/products/camiseta-merch-brandao/2.webp", "/products/camiseta-merch-brandao/3.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: false }, { label: "M", available: false }, { label: "G", available: false }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-manga-longa-preta-merch-brandao-oficial",
    title: "Camiseta Manga Longa Preta POMBA",
    priceBRL: 189,
    image: "/products/camiseta-manga-longa-preta-merch-brandao-oficial/1.webp",
    galleryImages: ["/products/camiseta-off-white-merch-brandao-oficial/2.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: false }, { label: "G", available: false }, { label: "GG", available: false }, { label: "EGG", available: true }, { label: "G1", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-off-white-merch-brandao-oficial",
    title: "Camiseta Off White RAIO X",
    priceBRL: 129,
    image: "/products/camiseta-off-white-merch-brandao-oficial/1.webp",
    galleryImages: ["/products/camiseta-off-white-merch-brandao-oficial/2.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: false }, { label: "M", available: false }, { label: "G", available: false }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-manga-longa-preta-merch-brandao-oficial-1",
    title: "Camiseta Manga Longa Preta WARZONE",
    priceBRL: 189,
    image: "/products/camiseta-manga-longa-preta-merch-brandao-oficial-1/1.webp",
    galleryImages: ["/products/camiseta-manga-longa-preta-merch-brandao-oficial-1/2.webp"],
    artistSlug: "brandao",
    isDropLive: true,
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: false }, { label: "GG", available: false }, { label: "EGG", available: true }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "bone-xtranho-preto",
    title: "Boné XTRANHO Preto",
    priceBRL: 129,
    image: "/products/bone-xtranho-preto/1.webp",
    galleryImages: ["/products/bone-xtranho-preto/2.webp"],
    artistSlug: "matue",
    category: "acessorios",
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "bone-xtranho-branco",
    title: "Boné XTRANHO Branco",
    priceBRL: 129,
    image: "/products/bone-xtranho-branco/1.webp",
    galleryImages: ["/products/bone-xtranho-branco/2.webp"],
    artistSlug: "matue",
    category: "acessorios",
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "protetor-bucal-xtranho-preto",
    title: "Protetor Bucal XTRANHO Preto",
    priceBRL: 99,
    image: "/products/protetor-bucal-xtranho-preto/1.webp",
    artistSlug: "matue",
    category: "acessorios",
    isSoldOut: true,
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "moletom-com-ziper-xtranho-preto",
    title: "Moletom com zíper XTRANHO Preto",
    priceBRL: 299,
    image: "/products/moletom-com-ziper-xtranho-preto/1.webp",
    galleryImages: ["/products/moletom-com-ziper-xtranho-preto/2.webp", "/products/moletom-com-ziper-xtranho-preto/3.webp"],
    artistSlug: "matue",
    category: "moletons",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: false }, { label: "GG", available: false }, { label: "EGG", available: false }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "regata-xtranho-estonada",
    title: "Regata XTRANHO Estonada",
    priceBRL: 129,
    image: "/products/regata-xtranho-estonada/1.webp",
    galleryImages: ["/products/regata-xtranho-estonada/2.webp"],
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "P", available: false }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-xtranho-preta",
    title: "Camiseta XTRANHO Preta",
    priceBRL: 129,
    image: "/products/camiseta-xtranho-preta/1.webp",
    galleryImages: ["/products/camiseta-xtranho-preta/2.webp"],
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-xtranho-off-white",
    title: "Camiseta XTRANHO Off White",
    priceBRL: 129,
    image: "/products/camiseta-xtranho-off-white/1.webp",
    galleryImages: ["/products/camiseta-xtranho-off-white/2.webp"],
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }, { label: "G1", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-isso-e-brasil-teto-wiu-merch-oficial",
    title: "Camiseta ISSO É BRASIL!",
    priceBRL: 149,
    image: "/products/camiseta-isso-e-brasil-teto-wiu-merch-oficial/1.webp",
    artistSlug: "teto",
    category: "camisetas",
    sizes: [{ label: "P", available: false }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-colapso-global-teto-wiu-merch-oficial",
    title: "Camiseta Colapso Global",
    priceBRL: 149,
    image: "/products/camiseta-colapso-global-teto-wiu-merch-oficial/1.webp",
    artistSlug: "teto",
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }, { label: "EGG", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "boneco-matue-rock-in-rio",
    title: "Boneco Matue Rock In Rio",
    priceBRL: 399,
    image: "/products/boneco-matue-rock-in-rio/1.webp",
    galleryImages: ["/products/boneco-matue-rock-in-rio/2.webp"],
    artistSlug: "matue",
    category: "acessorios",
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-portal-off-white",
    title: "Camiseta Portal Off White",
    priceBRL: 111,
    image: "/products/camiseta-portal-off-white/1.webp",
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "PP", available: true }, { label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "bone-trucker-333",
    title: "Boné Trucker 333",
    priceBRL: 111,
    image: "/products/bone-trucker-333/1.webp",
    galleryImages: ["/products/bone-trucker-333/2.webp"],
    artistSlug: "matue",
    category: "acessorios",
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-portal-preta",
    title: "Camiseta Portal Preta",
    priceBRL: 111,
    image: "/products/camiseta-portal-preta/1.webp",
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "PP", available: true }, { label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "hoodie-333-off-white",
    title: "Hoodie 333 Off White",
    priceBRL: 333,
    image: "/products/hoodie-333-off-white/1.webp",
    galleryImages: ["/products/hoodie-333-off-white/2.webp"],
    artistSlug: "matue",
    category: "moletons",
    sizes: [{ label: "PP", available: true }, { label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-o-som-off-white",
    title: "Camiseta O Som Off White",
    priceBRL: 111,
    image: "/products/camiseta-o-som-off-white/1.webp",
    galleryImages: ["/products/camiseta-o-som-off-white/2.webp"],
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "PP", available: true }, { label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "camiseta-o-som-preta",
    title: "Camiseta O Som Preta",
    priceBRL: 111,
    image: "/products/camiseta-o-som-preta/1.webp",
    galleryImages: ["/products/camiseta-o-som-preta/2.webp"],
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "PP", available: true }, { label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: false }],
    stockNote: "Enviado em security bag lacrada",
  },
  {
    handle: "baby-tee-333",
    title: "Baby Tee 333",
    priceBRL: 111,
    image: "/products/baby-tee-333/1.webp",
    galleryImages: ["/products/baby-tee-333/2.webp"],
    artistSlug: "matue",
    category: "camisetas",
    sizes: [{ label: "P", available: true }, { label: "M", available: true }, { label: "G", available: true }, { label: "GG", available: true }],
    stockNote: "Enviado em security bag lacrada",
  },
];
export function formatBRL(priceBRL: number): string {
  return `R$ ${priceBRL.toLocaleString("pt-BR")},00`;
}
